name: Docker Image CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN_2 }}
    - name: Build the Docker image
      run: |
        docker build . --file app/Dockerfile \
          --tag dockter2/ml-ops-com-vision:$GITHUB_SHA
    - name: Push the Docker image
      run: |
        docker push dockter2/ml-ops-com-vision:$GITHUB_SHA